### ISSUE TITLE
Problems with file path when there are spaces in names

### ISSUE THREAD

**Issue by viogp** [BatLabLancaster/preparenovonix#1]

**Comment by alanazulke** [comment]
File "C:/Users/Alana Zulke/PycharmProjects/Prepare novonix/ex.py", line 4
    infile = "C:\Users\Alana Zulke\Documents\Thermal analysis\GITT\Novonix Raw data\cell01.csv"
            ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by viogp** [comment]
For Windows paths this seems to work:
infile = r"C:\Users\Alana Zulke\Documents\Thermal analysis\GITT\Novonix Raw data\cell01.csv"
